### ISSUE TITLE
[Enhancement] API documentation in PT and EN

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [dssg-pt/Docker_COVID_API#1]
Since we are aiming at having the API publicly available to everyone, no matter what background they have, I think it would be useful to also have the API's documentation in EN.

**Comment by tensorfreitas** [comment]
You are right, we will update the documentation as soon as possible.

**Comment by JorgeMiguelGomes** [comment]
Closing issue because last update already includes EN/PT instructions.
